rename:
  "341": Hong Kong
  "331": Emiratos Árabes Unidos
  "438": Alemania
  "309": Corea del Sur
  "998": Destino indeterminado
  "398": Indeterminado (Asia)
  "498": Indeterminado (Europa)
  "298": Indeterminado (América)
  "198": Indeterminado (África)
  "444": Rusia
  "139": Tanzania
  "223": Puerto Rico
  "110": Costa de Marfil
  "109": R. D. del Congo
  "348": Yemen
  "123": Libia
  "283": Zona franca Zonamerica (Uruguay)
  "270": Zona franca Colón (Panamá)
  "504": Nueva Zelanda
  "320": Japón
  "337": Viet Nam
